create extension if not exists pgcrypto;
create type artwork_status as enum ('draft','processing','published','rejected');
create table public.artist_profiles(id uuid primary key references auth.users on delete cascade, display_name text not null, slug text unique not null, bio text, artist_statement text, instagram text not null, social_url text, location text, practice text, avatar_url text, cover_url text, is_public boolean not null default true, stripe_account_id text, referral_code text unique not null default encode(gen_random_bytes(6),'hex'), referred_by uuid references public.artist_profiles, commission_rate numeric(4,3) not null default .30, discounted_sales_remaining int not null default 0, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.artworks(id uuid primary key default gen_random_uuid(), artist_id uuid not null references public.artist_profiles on delete cascade, title text not null, medium text not null, year_created int not null check(year_created between 1500 and extract(year from now())::int), narrative text not null check(length(narrative)>=20), poster_base_price_cents int not null default 1200, original_for_sale boolean not null default false, original_price_cents int, original_width_cm numeric(7,2), original_height_cm numeric(7,2), original_status text not null default 'not_listed' check(original_status in ('not_listed','available','reserved','sold')), ships_from text, status artwork_status not null default 'draft', master_path text, process_video_path text, backing_path text, width_px int, height_px int, dpi int, created_at timestamptz default now(), published_at timestamptz, check(not original_for_sale or original_price_cents > 0));
create table public.poster_options(id uuid primary key default gen_random_uuid(), artwork_id uuid not null references public.artworks on delete cascade, label text not null, width_inches numeric(6,2) not null, height_inches numeric(6,2) not null, price_cents int not null check(price_cents > 0), ratio text not null, active boolean not null default true, unique(artwork_id,width_inches,height_inches));
create table public.artwork_files(id uuid primary key default gen_random_uuid(), artwork_id uuid not null references public.artworks on delete cascade, ratio text not null check(ratio in ('2:3','3:4','4:5','ISO','BACKING')), storage_path text not null, sha256 text, created_at timestamptz default now(), unique(artwork_id,ratio));
create table public.orders(id uuid primary key default gen_random_uuid(), buyer_id uuid references auth.users, artwork_id uuid not null references public.artworks, product_type text not null check(product_type in ('poster','original')), poster_option_id uuid references public.poster_options, stripe_checkout_id text unique, amount_cents int not null, shipping_cents int not null default 0, platform_fee_cents int not null, artist_amount_cents int not null, paid_at timestamptz, fulfilled_at timestamptz, download_token uuid unique default gen_random_uuid(), created_at timestamptz default now(), check((product_type='poster' and poster_option_id is not null) or (product_type='original' and poster_option_id is null)));
create table public.referral_rewards(id uuid primary key default gen_random_uuid(), referrer_id uuid not null references public.artist_profiles, referred_id uuid not null unique references public.artist_profiles, rewarded_at timestamptz default now());
alter table public.artist_profiles enable row level security; alter table public.artworks enable row level security; alter table public.artwork_files enable row level security; alter table public.orders enable row level security;
create policy "public profiles readable" on public.artist_profiles for select using(is_public or auth.uid()=id); create policy "artists insert self" on public.artist_profiles for insert with check(auth.uid()=id); create policy "artists update self" on public.artist_profiles for update using(auth.uid()=id) with check(auth.uid()=id);
create policy "published art readable" on public.artworks for select using(status='published' or auth.uid()=artist_id); create policy "artists manage art" on public.artworks for all using(auth.uid()=artist_id) with check(auth.uid()=artist_id);
create policy "buyers see orders" on public.orders for select using(auth.uid()=buyer_id); create policy "artist sees sales" on public.orders for select using(auth.uid()=(select artist_id from public.artworks where id=artwork_id));
-- Storage buckets: masters (private), provenance (private), products (private), previews (public).
-- A privileged worker should validate video duration/type and image dimensions, produce ratios + ZIP,
-- then set status='published'. Stripe webhook writes paid_at and returns a short-lived signed product URL.

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('artist-public','artist-public',true,10485760,array['image/jpeg','image/png','image/webp']) on conflict(id) do nothing;
create policy "artist media public read" on storage.objects for select using(bucket_id='artist-public');
create policy "artists upload own media" on storage.objects for insert to authenticated with check(bucket_id='artist-public' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "artists update own media" on storage.objects for update to authenticated using(bucket_id='artist-public' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "artists delete own media" on storage.objects for delete to authenticated using(bucket_id='artist-public' and (storage.foldername(name))[1]=auth.uid()::text);
